[package]
name = "instagras-object-storage"
version = "0.1.0"
authors = ["Alban GUILLET <albanguillet98@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
rusoto_connect = "0.41.0"
rusoto_core = "0.41.0"
rusoto_sqs = "0.41.0"
rusoto_s3 = "0.41.0"